"""initial

Revision ID: aae43e1e23be
Revises: 
Create Date: 2026-01-30 18:55:54.494969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae43e1e23be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('sheet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_templates_owner_user_id'), 'sheet_templates', ['owner_user_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=False),
    sa.Column('klass', sa.String(length=60), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('copper', sa.Integer(), nullable=False),
    sa.Column('aggression', sa.Integer(), nullable=False),
    sa.Column('kindness', sa.Integer(), nullable=False),
    sa.Column('intellect', sa.Integer(), nullable=False),
    sa.Column('fearlessness', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('humor', sa.Integer(), nullable=False),
    sa.Column('emotionality', sa.Integer(), nullable=False),
    sa.Column('sociability', sa.Integer(), nullable=False),
    sa.Column('responsibility', sa.Integer(), nullable=False),
    sa.Column('intimidation', sa.Integer(), nullable=False),
    sa.Column('attentiveness', sa.Integer(), nullable=False),
    sa.Column('learnability', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('stealth', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('counterattack', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('perm_armor', sa.Integer(), nullable=False),
    sa.Column('temp_armor', sa.Integer(), nullable=False),
    sa.Column('action_points', sa.Integer(), nullable=False),
    sa.Column('dodges', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('mana_max', sa.Integer(), nullable=False),
    sa.Column('energy_max', sa.Integer(), nullable=False),
    sa.Column('hp_per_level', sa.Integer(), nullable=False),
    sa.Column('mana_per_level', sa.Integer(), nullable=False),
    sa.Column('energy_per_level', sa.Integer(), nullable=False),
    sa.Column('level_up_rules', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('custom_values', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['sheet_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_owner_user_id'), 'characters', ['owner_user_id'], unique=False)
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('range', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('cost', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abilities_character_id'), 'abilities', ['character_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=120), nullable=False),
    sa.Column('armor', sa.String(length=120), nullable=False),
    sa.Column('back', sa.String(length=120), nullable=False),
    sa.Column('hands', sa.String(length=120), nullable=False),
    sa.Column('legs', sa.String(length=120), nullable=False),
    sa.Column('feet', sa.String(length=120), nullable=False),
    sa.Column('weapon1', sa.String(length=120), nullable=False),
    sa.Column('weapon2', sa.String(length=120), nullable=False),
    sa.Column('belt', sa.String(length=120), nullable=False),
    sa.Column('ring1', sa.String(length=120), nullable=False),
    sa.Column('ring2', sa.String(length=120), nullable=False),
    sa.Column('ring3', sa.String(length=120), nullable=False),
    sa.Column('ring4', sa.String(length=120), nullable=False),
    sa.Column('jewelry', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_character_id'), 'items', ['character_id'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('range', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('cost', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_character_id'), 'spells', ['character_id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hp_cost', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_character_id'), 'states', ['character_id'], unique=False)
    op.create_table('summons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('hp_ratio', sa.String(length=40), nullable=False),
    sa.Column('attack_ratio', sa.String(length=40), nullable=False),
    sa.Column('defense_ratio', sa.String(length=40), nullable=False),
    sa.Column('mana_ratio', sa.String(length=40), nullable=False),
    sa.Column('energy_ratio', sa.String(length=40), nullable=False),
    sa.Column('initiative_ratio', sa.String(length=40), nullable=False),
    sa.Column('luck_ratio', sa.String(length=40), nullable=False),
    sa.Column('steps_ratio', sa.String(length=40), nullable=False),
    sa.Column('attack_range_ratio', sa.String(length=40), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summons_character_id'), 'summons', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summons_character_id'), table_name='summons')
    op.drop_table('summons')
    op.drop_index(op.f('ix_states_character_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_spells_character_id'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_items_character_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_abilities_character_id'), table_name='abilities')
    op.drop_table('abilities')
    op.drop_index(op.f('ix_characters_owner_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_sheet_templates_owner_user_id'), table_name='sheet_templates')
    op.drop_table('sheet_templates')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
